version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: no # O container não reinicia automaticamente
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: